packages: []

onlyBuiltDependencies:
  - esbuild
  - "@parcel/watcher"
  - "@firebase/util"
  - nice-napi
  - protobufjs
  - lmdb
  - msgpackr-extract
strictDepBuilds: true
minimumReleaseAge: 4320
blockExoticSubdeps: true
verifyDepsBeforeRun: error
