name: deploy to dev
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 'deploy'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set frontend env
        run: mkdir -p src/environments && echo "${{ secrets.ENV_DEV }}" >> src/environments/environment.ts

      - name: update node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build

      - name: install dependencies in functions
        run: cd functions && npm ci

      - name: lint
        run: npm run lint

      # TODO: テストが整ったら入れる
      # - name: test
      #   run: npm run test

      - name: deploy to firebase
        uses: w9jds/firebase-action@v13.22.1
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_DEV }}
          PROJECT_ID: dev
