name: deploy to dev
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: 'deploy'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: update node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: run lint
        run: npm run lint

      # TODO: テストが整ったら入れる
      # - name: run test
      #   run: npm run test

      - name: copy index.html
        run: mkdir functions/lib && cp dist/musil/index.html functions/lib

      - name: install dependencies in functions
        run: cd functions && npm ci

      - name: deploy to firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_DEV }}
          PROJECT_ID: dev
