name: deploy to prod
on:
  push:
    tags:
      - 'v*'

jobs:
  prod:
    name: 'prod'
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: set frontend env
        run: mkdir -p src/environments && echo "${{ secrets.ENV_PROD }}" > src/environments/environment.prod.ts

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: update node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: lint
        run: pnpm lint

      - name: test
        run: pnpm test

      - name: build
        run: pnpm build --configuration production

      - name: install dependencies in functions
        working-directory: functions
        run: pnpm install --frozen-lockfile

      - name: lint functions
        working-directory: functions
        run: pnpm lint

      # TODO: テストが整ったら入れる
      # - name: test
      #   run: pnpm test

      - name: deploy to firebase
        uses: w9jds/firebase-action@v14.10.1
        with:
          args: deploy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_PROD }}
          PROJECT_ID: prod
